<a href="https://colab.research.google.com/github/maralerdene/DIVER/blob/main/Implementation_of_matrix_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Problem 1] Manually calculate the matrix product

In [7]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

print(a_ndarray @ b_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


[Problem 2] Calculation by NumPy function

In [8]:
#matmul
print('matmul:\n',np.matmul(a_ndarray,b_ndarray))

#dot

print('dot:\n',np.dot(a_ndarray,b_ndarray))

#@ operator
print('@:\n',(a_ndarray@b_ndarray))

matmul:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
dot:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
@:
 [[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


[Problem 3] Implementation of calculation of a certain element

In [13]:

result = []
for i in range(3): #this loops through columns of the matrix
    total = 0
    for j in range(3): #this loops through vector coordinates & rows of matrix
        total += a_ndarray[j] * b_ndarray[j][i]
    result.append(total)
print(result)


[array([ 14,  16, -18]), array([ 69,  66, -63]), array([-40,  34, -36])]


[Problem 4] Creating a function that performs matrix multiplication

In [14]:
def multiplyMatices(v, G):
    result = []
    for i in range(len(G[0])): #this loops through columns of the matrix
        total = 0
        for j in range(len(v)): #this loops through vector coordinates & rows of matrix
            total += v[j] * G[j][i]
        result.append(total)
    return result

print('result:\n',multiplyMatices(a_ndarray,b_ndarray))

result:
 [array([ 14,  16, -18]), array([ 69,  66, -63]), array([-40,  34, -36])]


[Problem 5] Judge the input whose calculation is not defined

In [17]:
def multiplyMatices(v, G):
    result = []
    for i in range(len(G[0])): #this loops through columns of the matrix
        total = 0
        for j in range(len(v)): #this loops through vector coordinates & rows of matrix
            total += v[j] * G[j][i]
        result.append(total)
    return result

print(a_ndarray.shape[0])
print(b_ndarray.shape)

if(a_ndarray.shape[0]!=b_ndarray.shape[1] or a_ndarray.shape[1]!=b_ndarray.shape[0]):
  print('matrices dimenstions is not compatible')
else:
  print('result:\n',multiplyMatices(a_ndarray,b_ndarray))

3
(3, 3)
result:
 [array([ 14,  16, -18]), array([ 69,  66, -63]), array([-40,  34, -36])]


[Problem 6] Transposition

In [20]:
#transpose matrices
print('before transpose:\n')
print(a_ndarray)
print('after transpose:\n')
np.transpose(a_ndarray) 

before transpose:

[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
after transpose:



array([[-1,  4,  7],
       [ 2, -5,  8],
       [ 3,  6, -9]])