<a href="https://colab.research.google.com/github/fkvivid/DIVER/blob/main/Leveraging_Object_Orientation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scaler = StandardScaler()
scaler.fit(X)
print("平均 :", scaler.mean_)
print("分散 :", scaler.var_)
X_std = scaler.transform(X)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.0764 0.0849 0.0105 0.0056]


In [2]:
scaler0 = StandardScaler()
scaler1 = StandardScaler()
scaler2 = StandardScaler()

[Problem 1] Enumeration of classes used so far

In [4]:
# from pandas     --> pd
# from numpy      --> np
# from matplotlib --> plt
# from seaborn    --> sns

# from sklearn    --> LinearRegression, train_test_split, mean_squared_error, SVR, 
# make_pipeline, StandardScaler, cross_val_score, DecisionTreeRegressor
# RandomForestRegressor


[Problem 2] Enumerate methods and instance variables that have been used so far

In [5]:
# from pandas     --> df = pd.read_csv('train.csv')
# from seaborn    --> sns.distplot(data['SalePrice'])
# from numpy      --> data['logSalePrice'] = np.log(data['SalePrice'])
# from matplotlib --> fig, ax1 = plt.subplots()
# from sklearn    --> model = LinearRegression()

In [6]:
import numpy as np
import pandas as pd

In [13]:
class ScratchStandardScaler():
    def __init__(self):
        pass

    def fit(self, X):
        self.mean_ = np.mean(X, axis=0)
        self.var_ = np.std(X - self.mean_, axis=0)
        return self

    def transform(self, X):
        return (X - self.mean_) / self.var_

    def fit_transform(self, X):
        return self.fit(X).transform(X)

In [14]:
import numpy as np
from sklearn.datasets import load_iris

data = load_iris()
X = data.data[:10]

scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("平均 : {}".format(scratch_scaler.mean_))
print("分散 : {}".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)
print(X_std)

平均 : [4.86 3.31 1.45 0.22]
分散 : [0.2764055  0.29137605 0.10246951 0.07483315]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


In [16]:
class ExampleClass():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2

example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8


[Problem 4] Creating a class that performs four arithmetic operations

In [23]:
class Arithmetic():
    """
    説明用の簡単なクラス

    Parameters
    ----------
    value : float or int
        初期値

    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, newVal):
        if type(newVal) != int and type(newVal) != float:
          raise ValueError('input is must be number')
        self.value += newVal
    def subtract(self, newVal):
        if type(newVal) != int and type(newVal) != float:
          raise ValueError('input is must be number')
        self.value -= newVal
    def multiply(self, newVal):
        if type(newVal) != int and type(newVal) != float:
          raise ValueError('input is must be number')
        self.value += newVal
    def divide(self, newVal):
        if type(newVal) != int and type(newVal) != float:
          raise ValueError('input is must be number')
        self.value += newVal

example = Arithmetic(5)
print("value : {}".format(example.value))
example.add(1)
print("value : {}".format(example.value))
example.subtract(1)
print("value : {}".format(example.value))
example.multiply(1)
print("value : {}".format(example.value))
example.divide(1)
print("value : {}".format(example.value))
example.add('1')
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 6
value : 5
value : 6
value : 7


ValueError: ignored